TWEAK_NAME = Eneko
Eneko_FILES = Eneko.m
Eneko_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
Eneko_FRAMEWORKS = UIKit AVFoundation
Eneko_LIBRARIES = gcuniversal

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
