BUNDLE_NAME = EnekoPreferences
EnekoPreferences_FILES = $(wildcard Controllers/*.m Cells/*.m)
EnekoPreferences_FRAMEWORKS = UIKit
EnekoPreferences_PRIVATE_FRAMEWORKS = Preferences
EnekoPreferences_LIBRARIES = gcuniversal
EnekoPreferences_INSTALL_PATH = /Library/PreferenceBundles
EnekoPreferences_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
