#!/bin/sh

echo ""
echo "       ____       "
echo "  _[]_/____\__n_  "
echo " |_____.--.__()_| "
echo " |     //# \\    | "
echo " |     \\__//    | "
echo " |     '--'     | "
echo " '--------------' "
echo ""
echo "Thank You For Installing Eneko 1.1.2 🤗"
echo ""
